fix: add a newline to the password decrypt command
cloudposse/terraform-aws-iam-user pull request #30
Opened 2023-10-03 01:42 UTC by b1n9s

The output of the command `echo "${encrypted_password}" | base64 --decode | keybase pgp decrypt` does not have a newline character at the end of the line, so the decrypted password is either mixed with the prompt (bash) or has a trailing character ('%' or '#' in zsh).

## what

- add a newline to the decrypt password

## why

The output of the command `echo "${encrypted_password}" | base64 --decode | keybase pgp decrypt` does not have a newline character at the end of the line, so the decrypted password is either mixed with prompt (bash) or has a trailing character ('%' or '#' in zsh).
This commit pipes the decrypted password to echo to force a newline.

## references

https://zsh.sourceforge.io/Doc/Release/Options.html#Prompting

2024-03-02 11:33 UTC, hans-d commented
/terratest

2024-03-03 20:01 UTC, hans-d commented
@b1n9s can you update the readme as per the failing readme check ?

2024-04-10 15:05 UTC, goruha requested changes
Check comment ^

2024-04-24 08:34 UTC, b1n9s commented
@goruha, sorry I lost track of this PR, the purpose of this PR is to add a new line to the output, so the trailing '%' won't be shown in the output in zsh.

change to `xargs echo -n` will just be the same as it was.

2024-06-06 18:03 UTC, goruha commented
/terratest

2026-01-07 21:44 UTC, closed without merging